### ISSUE TITLE
cargo-rpm: support cargo-release versions

### ISSUE THREAD

**Issue by cardoe** [iqlusion-io/crates#38]
So I use https://crates.io/crates/cargo-release to manage my releases to crates.io but I found out the versions that it uses result in build failures with cargo-rpm. e.g. https://gitlab.com/cardoe/sakcl/-/jobs/71676981 The style of versioning "0.1.1-alpha.0" is actually proper per https://semver.org/#spec-item-11 which is what Rust and Cargo follow.

I have a few non-public projects that I build with RPMs and build directly with rpmbuild and a shell script that substitutes values in. The process I followed was https://fedoraproject.org/wiki/Packaging:Versioning#Prerelease_versions

**Comment by tarcieri** [comment]
Well, it's failing here:

```
$ cargo rpm build
    Finished release [optimized] target(s) in 0.0 secs
    Building sakcl-0.1.1-alpha.0.rpm (using rpmbuild 4.11.3)

error: error running /usr/bin/rpmbuild (exit status: exit code: 1)
ERROR: Job failed: exit code 1
```

Perhaps I should have it print "rerun with -v to see errors", but that's the next step. I can try it out on a dummy crate if I have time.

**Comment by tarcieri** [comment]
Moving this issue to the project's new home:

https://github.com/RustRPM/cargo-rpm/issues/3
